name: Deploy Containerized App with OIDC

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Azure Login with OIDC
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Log in to Azure Container Registry (ACR)
      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Build and push Docker image to ACR
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-app:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-app:latest

      # Deploy image to Azure Container Apps
      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name my-container-app \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/my-app:latest
